In [2]:
import pandas as pd
import numpy as np

file_path = "../dataset/ecommerce_customer_behavior_dataset_v2.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (17049, 18)

In [3]:
print("First 5 rows:")
display(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

First 5 rows:

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_000001-1,CUST_00001,2023-05-29,40,Male,Ankara,Books,29.18,1,0.00,29.18,Digital Wallet,Mobile,14,9,True,13,4
1,ORD_000001-2,CUST_00001,2023-10-12,40,Male,Ankara,Home & Garden,644.40,1,138.05,506.35,Credit Card,Desktop,14,8,True,6,2
2,ORD_000001-3,CUST_00001,2023-12-05,40,Male,Ankara,Sports,332.82,5,0.00,1664.10,Credit Card,Mobile,15,10,True,9,4
3,ORD_000002-1,CUST_00002,2023-05-11,33,Male,Istanbul,Food,69.30,5,71.05,275.45,Digital Wallet,Desktop,16,13,True,4,4
4,ORD_000002-2,CUST_00002,2023-06-16,33,Male,Istanbul,Beauty,178.15,3,0.00,534.45,Credit Card,Mobile,14,7,True,6,4

Column names:
['Order_ID', 'Customer_ID', 'Date', 'Age', 'Gender', 'City', 'Product_Category', 'Unit_Price', 'Quantity', 'Discount_Amount', 'Total_Amount', 'Payment_Method', 'Device_Type', 'Session_Duration_Minutes', 'Pages_Viewed', 'Is_Returning_Customer', 'Delivery_Time_Days', 'Customer_Rating']

Data types:
Order_ID                        str
Customer_ID                     str
Date                            str
Age                           int64
Gender                          str
City                            str
Product_Category                str
Unit_Price                  float64
Quantity                      int64
Discount_Amount             float64
Total_Amount                float64
Payment_Method                  str
Device_Type                     str
Session_Duration_Minutes      int64
Pages_Viewed                  int64
Is_Returning_Customer          bool
Delivery_Time_Days            int64
Customer_Rating               int64
dtype: object

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values in each column:
Order_ID                    0
Customer_ID                 0
Date                        0
Age                         0
Gender                      0
City                        0
Product_Category            0
Unit_Price                  0
Quantity                    0
Discount_Amount             0
Total_Amount                0
Payment_Method              0
Device_Type                 0
Session_Duration_Minutes    0
Pages_Viewed                0
Is_Returning_Customer       0
Delivery_Time_Days          0
Customer_Rating             0
dtype: int64

Total missing values: 0

Duplicate rows: 0

In [5]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print("Date converted successfully!")
print(df['Date'].dtype)
print("Invalid dates:", df['Date'].isnull().sum())

Date converted successfully!
datetime64[us]
Invalid dates: 0

In [6]:
print("Age:", df['Age'].min(), "to", df['Age'].max())
print("Quantity:", df['Quantity'].min(), "to", df['Quantity'].max())
print("Unit Price:", df['Unit_Price'].min(), "to", df['Unit_Price'].max())
print("Discount Amount:", df['Discount_Amount'].min(), "to", df['Discount_Amount'].max())
print("Total Amount:", df['Total_Amount'].min(), "to", df['Total_Amount'].max())
print("Session Duration:", df['Session_Duration_Minutes'].min(), "to", df['Session_Duration_Minutes'].max())
print("Pages Viewed:", df['Pages_Viewed'].min(), "to", df['Pages_Viewed'].max())
print("Delivery Time:", df['Delivery_Time_Days'].min(), "to", df['Delivery_Time_Days'].max())
print("Customer Rating:", df['Customer_Rating'].min(), "to", df['Customer_Rating'].max())

print("\nProduct Categories:")
print(df['Product_Category'].unique())

print("\nPayment Methods:")
print(df['Payment_Method'].unique())

print("\nDevice Types:")
print(df['Device_Type'].unique())

Age: 18 to 75
Quantity: 1 to 5
Unit Price: 5.05 to 7900.01
Discount Amount: 0.0 to 6538.29
Total Amount: 6.21 to 37852.05
Session Duration: 4 to 26
Pages Viewed: 1 to 18
Delivery Time: 1 to 25
Customer Rating: 1 to 5

Product Categories:
<ArrowStringArray>
[        'Books', 'Home & Garden',        'Sports',          'Food',
        'Beauty',          'Toys',       'Fashion',   'Electronics']
Length: 8, dtype: str

Payment Methods:
<ArrowStringArray>
[  'Digital Wallet',      'Credit Card',    'Bank Transfer',
       'Debit Card', 'Cash on Delivery']
Length: 5, dtype: str

Device Types:
<ArrowStringArray>
['Mobile', 'Desktop', 'Tablet']
Length: 3, dtype: str

In [7]:
# Create a cleaned copy
df_clean = df.copy()

# Sort records by date
df_clean = df_clean.sort_values('Date').reset_index(drop=True)

print("Cleaned dataset created successfully!")
print("Shape:", df_clean.shape)
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())

Cleaned dataset created successfully!
Shape: (17049, 18)
Missing values: 0
Duplicate rows: 0

In [8]:
cleaned_path = "../dataset/ecommerce_customer_behavior_cleaned.csv"

df_clean.to_csv(cleaned_path, index=False)

print("Cleaned dataset saved successfully!")
print(cleaned_path)

Cleaned dataset saved successfully!
../dataset/ecommerce_customer_behavior_cleaned.csv

In [9]:
df_clean.describe()
df_clean.describe(include='object')
print("Dataset shape:", df_clean.shape)

print("\nColumn names:")

print(df_clean.columns.tolist())

Dataset shape: (17049, 18)

Column names:
['Order_ID', 'Customer_ID', 'Date', 'Age', 'Gender', 'City', 'Product_Category', 'Unit_Price', 'Quantity', 'Discount_Amount', 'Total_Amount', 'Payment_Method', 'Device_Type', 'Session_Duration_Minutes', 'Pages_Viewed', 'Is_Returning_Customer', 'Delivery_Time_Days', 'Customer_Rating']

C:\Users\home\AppData\Local\Temp\ipykernel_10744\3948457435.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_clean.describe(include='object')

In [10]:
df_clean.describe(include='str')
print("Dataset shape:", df_clean.shape)

print("\nColumn names:")
print(df_clean.columns.tolist())

Dataset shape: (17049, 18)

Column names:
['Order_ID', 'Customer_ID', 'Date', 'Age', 'Gender', 'City', 'Product_Category', 'Unit_Price', 'Quantity', 'Discount_Amount', 'Total_Amount', 'Payment_Method', 'Device_Type', 'Session_Duration_Minutes', 'Pages_Viewed', 'Is_Returning_Customer', 'Delivery_Time_Days', 'Customer_Rating']

In [11]:
numeric_summary = df_clean[
    [
        'Age',
        'Unit_Price',
        'Quantity',
        'Discount_Amount',
        'Total_Amount',
        'Session_Duration_Minutes',
        'Pages_Viewed',
        'Delivery_Time_Days',
        'Customer_Rating'
    ]
].describe().round(2)

display(numeric_summary)

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00
mean,34.95,447.90,3.01,69.79,1277.44,14.54,9.00,6.50,3.90
std,11.05,722.32,1.42,240.70,2358.44,2.93,2.26,3.49,1.13
min,18.00,5.05,1.00,0.00,6.21,4.00,1.00,1.00,1.00
25%,26.00,73.26,2.00,0.00,172.97,13.00,7.00,4.00,3.00
50%,35.00,174.68,3.00,0.00,455.85,15.00,9.00,6.00,4.00
75%,42.00,494.57,4.00,32.71,1267.75,17.00,11.00,8.00,5.00
max,75.00,7900.01,5.00,6538.29,37852.05,26.00,18.00,25.00,5.00

In [12]:
print("Total Sales:", round(df_clean['Total_Amount'].sum(), 2))
print("Average Order Value:", round(df_clean['Total_Amount'].mean(), 2))
print("Total Quantity Sold:", df_clean['Quantity'].sum())
print("Average Customer Rating:", round(df_clean['Customer_Rating'].mean(), 2))
print("Average Delivery Time:", round(df_clean['Delivery_Time_Days'].mean(), 2))
print("Returning Customer Rate:",
      round(df_clean['Is_Returning_Customer'].mean() * 100, 2), "%")

Total Sales: 21779052.59
Average Order Value: 1277.44
Total Quantity Sold: 51341
Average Customer Rating: 3.9
Average Delivery Time: 6.5
Returning Customer Rate: 88.21 %

In [13]:
numeric_summary = df_clean[
    [
        'Age',
        'Unit_Price',
        'Quantity',
        'Discount_Amount',
        'Total_Amount',
        'Session_Duration_Minutes',
        'Pages_Viewed',
        'Delivery_Time_Days',
        'Customer_Rating'
    ]
].describe().round(2)

display(numeric_summary)

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00,17049.00
mean,34.95,447.90,3.01,69.79,1277.44,14.54,9.00,6.50,3.90
std,11.05,722.32,1.42,240.70,2358.44,2.93,2.26,3.49,1.13
min,18.00,5.05,1.00,0.00,6.21,4.00,1.00,1.00,1.00
25%,26.00,73.26,2.00,0.00,172.97,13.00,7.00,4.00,3.00
50%,35.00,174.68,3.00,0.00,455.85,15.00,9.00,6.00,4.00
75%,42.00,494.57,4.00,32.71,1267.75,17.00,11.00,8.00,5.00
max,75.00,7900.01,5.00,6538.29,37852.05,26.00,18.00,25.00,5.00

In [14]:
print("Total Sales:", round(df_clean['Total_Amount'].sum(), 2))
print("Average Order Value:", round(df_clean['Total_Amount'].mean(), 2))
print("Total Quantity Sold:", df_clean['Quantity'].sum())
print("Average Customer Rating:", round(df_clean['Customer_Rating'].mean(), 2))
print("Average Delivery Time:", round(df_clean['Delivery_Time_Days'].mean(), 2))
print("Returning Customer Rate:",
      round(df_clean['Is_Returning_Customer'].mean() * 100, 2), "%")

Total Sales: 21779052.59
Average Order Value: 1277.44
Total Quantity Sold: 51341
Average Customer Rating: 3.9
Average Delivery Time: 6.5
Returning Customer Rate: 88.21 %

In [15]:
category_sales = (
    df_clean.groupby('Product_Category')['Total_Amount']
    .sum()
    .sort_values(ascending=False)
    .round(2)
)

display(category_sales)

Product_Category
Electronics      10481897.65
Home & Garden     4023903.94
Sports            3205086.99
Fashion           1577035.70
Toys              1014237.53
Beauty             694437.02
Food               422054.65
Books              360399.11
Name: Total_Amount, dtype: float64

In [ ]:
payment_sales = (
    df_clean.groupby('Payment_Method')['Total_Amount']
    .sum()
    .sort_values(ascending=False)
    .round(2)
)

display(payment_sales)

In [ ]:
device_sales = (
    df_clean.groupby('Device_Type')['Total_Amount']
    .sum()
    .sort_values(ascending=False)
    .round(2)
)

display(device_sales)

In [16]:
monthly_sales = (
    df_clean.groupby(df_clean['Date'].dt.to_period('M'))['Total_Amount']
    .sum()
)

monthly_sales.index = monthly_sales.index.astype(str)

display(monthly_sales.round(2))

Date
2023-01    1311603.21
2023-02    1409777.29
2023-03    1458005.58
2023-04    1499648.03
2023-05    1483511.61
2023-06    1380984.94
2023-07    1560046.14
2023-08    1510999.75
2023-09    1502164.37
2023-10    1536847.33
2023-11    1446439.79
2023-12    1586213.77
2024-01    1490824.78
2024-02    1329884.01
2024-03    1272101.99
Name: Total_Amount, dtype: float64

In [17]:
correlation_matrix = df_clean[
    [
        'Age',
        'Unit_Price',
        'Quantity',
        'Discount_Amount',
        'Total_Amount',
        'Session_Duration_Minutes',
        'Pages_Viewed',
        'Delivery_Time_Days',
        'Customer_Rating'
    ]
].corr().round(2)

display(correlation_matrix)

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
Age,1.00,-0.00,0.00,0.01,-0.00,0.01,-0.01,0.00,-0.00
Unit_Price,-0.00,1.00,-0.00,0.48,0.87,-0.01,0.02,-0.02,-0.00
Quantity,0.00,-0.00,1.00,0.13,0.26,-0.01,-0.00,0.00,-0.00
Discount_Amount,0.01,0.48,0.13,1.00,0.46,-0.01,-0.00,-0.01,0.00
Total_Amount,-0.00,0.87,0.26,0.46,1.00,-0.01,0.01,-0.02,0.00
Session_Duration_Minutes,0.01,-0.01,-0.01,-0.01,-0.01,1.00,0.01,0.00,-0.00
Pages_Viewed,-0.01,0.02,-0.00,-0.00,0.01,0.01,1.00,0.01,-0.01
Delivery_Time_Days,0.00,-0.02,0.00,-0.01,-0.02,0.00,0.01,1.00,-0.01
Customer_Rating,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.01,-0.01,1.00

In [18]:
numeric_columns = [
    'Age',
    'Unit_Price',
    'Quantity',
    'Discount_Amount',
    'Total_Amount',
    'Session_Duration_Minutes',
    'Pages_Viewed',
    'Delivery_Time_Days',
    'Customer_Rating'
]

outlier_summary = {}

for col in numeric_columns:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df_clean[col] < lower) | (df_clean[col] > upper)).sum()

    outlier_summary[col] = count

outlier_summary = pd.Series(outlier_summary).sort_values(ascending=False)

display(outlier_summary)

Discount_Amount             2789
Total_Amount                1943
Unit_Price                  1757
Delivery_Time_Days           475
Session_Duration_Minutes      85
Age                           50
Pages_Viewed                   1
Quantity                       0
Customer_Rating                0
dtype: int64